name: Reusable workflow - Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Use checkout-repository-cache
        uses: actions/cache@v3
        id: checkout-repository-cache
        with:
          path: ./*
          key: checkout-repository-cache-${{ github.sha }}
      
      - name: Build project
        shell: bash
        run: npm run manager:build
      
      - name: Clean node_modules directory
        shell: bash
        run: rm -fr node_modules
      
      - name: Create build-cache
        uses: actions/cache@v3
        id: build-cache
        with:
          path: ./*
          key: build-cache-${{ github.sha }}
          