name: Reusable workflow - Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "TEST Reusable workflows - build.yml "
        shell: bash
        run: | 
          echo "PRINT Reusable workflows - build.yml ${{ env.NODE_BUILD_VERSION }}"
          ls -ltr ../
          echo $GITHUB_WORKSPACE
          ls -ltr $GITHUB_WORKSPACE

