name: Node Manager reusable workflows - Build

on:
  workflow_call:

jobs:
  build:
    name: Build project [github-node-manager-reusable-workflows/build]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch checkout-repository-cache
        uses: actions/cache@v3
        id: checkout-repository-cache
        with:
          path: ./*
          key: checkout-repository-cache-${{ github.sha }}

      - name: Build project via node-manager
        shell: bash
        run: npm run manager:build

      - name: Remove node_modules directory
        shell: bash
        run: rm -fr node_modules

      - name: Create build-cache
        uses: actions/cache@v3
        id: build-cache
        with:
          path: ./*
          key: build-cache-${{ github.sha }}
