name: Reusable workflow - Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Use checkout-repository-cache
        uses: actions/cache@v3
        id: checkout-repository-cache
        with:
          path: ./*
          key: checkout-repository-cache-${{ github.sha }}
      
      - name: Build project
        shell: bash
        run: npm run manager:build
      
      # Doit on supprimer ICI ??? Ca ne serait pas mieux de le faire lors des tests ?
      - name: Clean node_modules directory
        shell: bash
        run: rm -fr node_modules
      
      - name: Create build-cache
        uses: actions/cache@v3
        id: build-cache
        with:
          path: ./*
          key: build-cache-${{ github.sha }}
      
      - name: "TEST Reusable workflows - build.yml "
        shell: bash
        run: | 
          echo "PRINT Reusable workflows - build.yml ${{ env.NODE_BUILD_VERSION }}"
          pwd
          ls -ltr 
          echo $GITHUB_WORKSPACE
          ls -ltr $GITHUB_WORKSPACE

