name: Reusable workflow - Build

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Build on reusable workflow"
        shell: bash
        run: echo "TEST reusable workflow"

