name: Reusable workflow - Build

on:
  push:
    branches:
      - release/**
      - develop
      - feature/**
  workflow_call:

jobs:
  # call_workflow_setup:
  #   name: Calling reusable workflow setup
  #   uses: ./.github/workflows/setup.yml
  #   runs-on: ubuntu-latest
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -name: Build on reusable workflow
      shell: bash
      run: echo "TEST reusable workflow"

