name: Reusable workflow - Build

on:
  push:
    branches:
      - release/**
      - develop
      - feature/**
  workflow_call:

jobs:
  # call_workflow_setup:
  #   name: Calling reusable workflow setup
  #   uses: ./.github/workflows/setup.yml
  #   runs-on: ubuntu-latest
  build:
    - name: Build
    shell: bash
    run: echo "BUILD on reusable workflow"

