name: Reusable workflow - Publish

on:
  workflow_call:

jobs:
  publish:
    name: Publish and Tag
    runs-on: ubuntu-latest
    
    steps:
      - name: Use build-cache
        uses: actions/cache@v3
        id: build-cache
        with:
          path: ./*
          key: build-cache-${{ github.sha }}
      
      - name: NPM publish
        shell: bash
        run: |
          OPTS=();
          if [[ $(npm pkg get version) == *"-"* ]]; then OPTS+=('--tag=next') ; fi
          if [[ $(npm pkg get workspaces) != "{}" ]]; then OPTS+=('--workspaces') ; fi
          npm publish $OPTS --access=public

      - name: Prepare git
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: Git Tag
        shell: bash
        run: |
          TAG_VERSION=$(npm pkg get version | xargs)
          git tag $TAG_VERSION
          git push origin $TAG_VERSION