name: Node reusable workflows - Publish

on:
  workflow_call:
    secrets:
      auth-token:
        required: true

jobs:
  publish:
    name: Publish packages [github-node-reusable-workflows/publish]
    runs-on: ubuntu-latest

    steps:
      - name: Fetch build-cache
        uses: actions/cache@v3
        id: build-cache
        with:
          path: |
            ./*
            !./node_modules
          key: build-cache-${{ github.sha }}

      - name: Publish to registry
        shell: bash
        run: |
          OPTS=();
          if [[ $(npm pkg get version) == *"-"* ]]; then OPTS+=('--tag=next') ; fi
          if [[ $(npm pkg get workspaces) != "{}" ]]; then OPTS+=('--workspaces') ; fi
          npm publish $OPTS --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.auth-token }}

      - name: Configure git
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: Tag commit
        shell: bash
        run: |
          TAG_VERSION=$(npm pkg get version | xargs)
          git tag $TAG_VERSION
          git push origin $TAG_VERSION
