name: Node Manager reusable workflows - Setup

on:
  workflow_call:
    inputs:
      branch-ref:
        required: true
        type: string
      node-version:
        required: false
        type: string
        default: 16
      os:
        required: false
        type: string
        default: ubuntu-latest
      jfrog-artifactory:
        required: false
        type: boolean
        default: false
    secrets:
      github-token:
        required: false
      scope:
        required: false
      registry-url:
        required: false
      auth-token:
        required: false

env:
  standard-setup: ${{ inputs.jfrog-artifactory != true }}
  jfrog-artifactory-setup: ${{ inputs.jfrog-artifactory == true }}

jobs:
  setup:
    name: Setup for Node.js ${{ inputs.node-version }} [github-node-manager-reusable-workflows/setup]
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repository ${{ inputs.branch-ref }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-ref }}
          # token: ${{ secrets.github-token }}


      # Standard setup
      - name: Install Node.js ${{ inputs.node-version }}
        if: ${{ env.standard-setup == 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: ./package-lock.json
          scope: ${{ secrets.scope }}
          registry-url: ${{ secrets.registry-url }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.auth-token }}
      # /Standard setup

      # JFrog Artifactory setup because it uses _auth instead of standard _authToken
      - name: Install Node.js ${{ inputs.node-version }} for JFrog Artifactory
        if: ${{ env.jfrog-artifactory-setup == 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Generate .npmrc for JFrog Artifactory
        if: ${{ env.jfrog-artifactory-setup == 'true' }}
        shell: bash
        run: |
          SCOPE=${{ secrets.scope }}
          REGISTRY=${{ secrets.registry-url }}
          AUTH=${{ secrets.auth-token }}
          echo "${SCOPE}:registry=${REGISTRY}" >> .npmrc
          echo "//${REGISTRY##*//}:_auth=${AUTH}" >> .npmrc
      # /JFrog Artifactory


      - name: Install dependencies
        run: npm ci

      - name: Create cache
        uses: actions/cache@v3
        id: checkout-repository-cache
        with:
          path: ./*
          key: checkout-repository-cache-${{ github.sha }}
