name: Node Manager reusable workflows - Setup

on:
  workflow_call:
    inputs:
      branch-ref:
        required: true
        type: string
      node-version:
        required: false
        type: string
        default: 16
      os:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  setup:
    name: Setup for Node.js ${{ inputs.node-version }} [github-node-manager-reusable-workflows/setup]
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository ${{ inputs.branch-ref }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-ref }}
          token: ${{ secrets.GLOBAL_ACCESS_TOKEN }}

      - name: Install Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: ./package-lock.json

#      - name: Install Node.js ${{ inputs.node-version }}
#        if:  ${{ inputs.npm-registry == 'private' }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: ${{ inputs.node-version }}
#          # cache: "npm"
#          # cache-dependency-path: ./package-lock.json
#          scope: '@absolunet-sparks' #${{ secrets.NPMRC_JFROG_ARTIFACTORY_NAMESPACE }}
#          registry-url: 'https://absolunet.jfrog.io/artifactory/api/npm/abso_npm_sparks/' #${{ secrets.NPMRC_JFROG_ARTIFACTORY_URL }}
#          always-auth: true
#          # token: ${{ secrets.NPMRC_JFROG_ARTIFACTORY_TOKEN }}
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPMRC_JFROG_ARTIFACTORY_TOKEN }}
#
#      - name: Install Node.js ${{ inputs.node-version }} with private access
#        if:  ${{ inputs.npm-registry == 'public' }}
#        uses: actions/setup-node@v3
#        with:
#          always-auth: true
#          node-version: ${{ inputs.node-version }}
#          cache: "npm"
#          cache-dependency-path: ./package-lock.json
#          token: ${{ secrets.NPMRC_NPMJS_REGISTRY_TOKEN }}
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPMRC_NPMJS_REGISTRY_TOKEN }}

      # Patch step for JFrog Artifactory that uses _auth instead of standard _authToken
      - name: Generate .npmrc for JFrog Artifactory
        shell: bash
        run: |
          SCOPE=${{ secrets.JFROG_ARTIFACTORY_NPM_SPARKS_SCOPE }}
          REGISTRY=${{ secrets.JFROG_ARTIFACTORY_NPM_SPARKS_REGISTRY }}
          AUTH=${{ secrets.JFROG_ARTIFACTORY_NPM_SPARKS_AUTH }}
          echo "${SCOPE}:registry=${REGISTRY}" >> .npmrc
          echo "//${REGISTRY##*//}:_auth=${AUTH}" >> .npmrc

      - name: Install dependencies
        run: npm ci

      - name: Create cache
        uses: actions/cache@v3
        id: checkout-repository-cache
        with:
          path: ./*
          key: checkout-repository-cache-${{ github.sha }}
