name: Reusable workflow - Setup

on:
  workflow_call:
    inputs:
      branch-ref:
        required: true
        type: string
      node-version:
        required: false
        type: string
        default: 16
      os:
        required: false
        type: string
        default: ubuntu-latest
      node-auth-token:
        required: false
        type: string
      node-registry-url:
        required: false
        type: string
      node-scope:
        required: false
        type: string

jobs:
  setup:
    name: Setup with Node version ${{ inputs.node-version }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout repository ${{ inputs.branch-ref }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch-ref }}
          token: ${{ secrets.GLOBAL_ACCESS_TOKEN }}
      
      - name: PRINT INPUTS
        run: |
          echo ${{ inputs.branch-ref }}
          echo ${{ inputs.node-auth-token }}
          echo ${{ inputs.node-registry-url }}
          echo ${{ inputs.node-scope }}

      - name: Setup Node ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: ./package-lock.json
          scope: ${{ inputs.node-scope }}
          registry-url: ${{ inputs.node-registry-url }}
        env:
          NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create Cache
        uses: actions/cache@v3
        id: checkout-repository-cache
        with:
          path: ./*
          key: checkout-repository-cache-${{ github.sha }}
