name: Reusable workflow - Setup

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: 16
      os:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  setup:
    name: Setup node version ${{ inputs.node_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository ${{ github.head_ref }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: ./checkout-directory
      - name: Setup Node ${{ inputs.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: "npm"
          cache-dependency-path: ./checkout-directory/package-lock.json
      - name: TEST
        run: |
          pwd
          ls -ltr
          echo "GITHUB WORKSPACE"
          ls -ltr $GITHUB_WORKSPACE/checkout-directory