name: Reusable workflow - Test

on:
  workflow_call:
    # inputs:
    #   node-version:
    #     required: false
    #     type: string
    #     default: >-
#        ["16", "14"]
    #   os:
    #     required: false
    #     type: string
    #     default: ubuntu-latest

jobs:
  test:
    strategy:
      matrix:
        node-version: [16, 14]
        os: [ubuntu-latest]
        # node-version: ${{fromJson(inputs.node-version)}}
        # os: ${{fromJson(inputs.os)}}

    name: Running Test with node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Use build-cache
        uses: actions/cache@v3
        id: build-cache
        with:
          path: ./*
          key: build-cache-${{ github.sha }}
      - name: TEST
        run: git branch
      # - name: Install dependencies
      #   run: npm ci
      
      # - name: Run test
      #   run: npm test