name: Node reusable workflows - Test

on:
  workflow_call:

jobs:
  test:
    strategy:
      matrix:
        node-version: [16, 14]
        os: [ubuntu-latest, windows-latest]

    name: Run tests on ${{ matrix.os }} with Node.js ${{ matrix.node-version }} [github-node-reusable-workflows/test]
    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/cache/issues/591
      # https://github.com/actions/cache/issues/576
      - name: Use GNU tar instead BSD tar
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"

      - name: Fetch build-cache
        uses: actions/cache@v3
        id: build-cache
        with:
          path: |
            ./*
            !./node_modules
          key: build-cache-${{ github.sha }}

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
