name: Reusable workflow - Version Bump

on:
  workflow_call:

jobs:
  version_change:
    name: Version change
    runs-on: ubuntu-latest
    
    steps:
      - name: Use checkout-repository-cache
        uses: actions/cache@v3
        id: checkout-repository-cache
        with:
          path: ./*
          key: checkout-repository-cache-${{ github.sha }}
      
      - name: Get npm-config-release
        id: get-npm-config-release
        shell: bash
        run: |
          REF_BRANCH=${{ github.head_ref }}
          echo "::set-output name=branch_suffix::$(echo ${REF_BRANCH##*/})"

      - name: Create a release version bump - ${{ steps.get-npm-config-release.outputs.branch_suffix }}
        shell: bash
        run: npm run manager:version --release=${{ steps.get-npm-config-release.outputs.branch_suffix }}
      
      - name: Get Package Version
        id: get-package-info
        shell: bash
        run: echo "::set-output name=package_version::$(npm pkg get version)"
      
      - uses: absolunet/github-update-changelog-action@main
        with:
          release-version: ${{ steps.get-package-info.outputs.package_version }}
      
      - name: Prepare git
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"

      - name: Commit Change
        shell: bash
        run: |
          git status
          git add -u
          git commit -m "Automated Version bump - ${{ steps.get-package-info.outputs.package_version }}"
          git push origin ${{ github.head_ref }}